# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SARView
                                 A QGIS plugin
 Plugin that help you visualize SAR data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-15
        copyright            : (C) 2026 by Mohamad El Moussawi
        email                : mohamad.elmoussawi@mail.polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SARView class from file SARView.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SARView import SARView
    return SARView(iface)
